kafka:
    topic:
        subscription-created: subscription-created-topic
server:
    port: 8081
spring:
    application:
        name: subcription-microservice
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:subscriptiondb
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    cloud:
      aws:
        region:
          static: eu-west-1
        credentials:
          access-key: ${AWS_ACCESS_KEY_ID}
          secret-key: ${AWS_SECRET_ACCESS_KEY}
        sqs:
          endpoint: https://sqs.eu-west-1.amazonaws.com

aws:
  sqs:
    queue:
      subscription-events: ${SQS_SUBSCRIPTION_QUEUE_URL:https://sqs.eu-west-1.amazonaws.com/286646249098/subscription-events}

logging:
  level:
    com.amazonaws: DEBUG
    io.awspring.cloud: DEBUG