spring:
  application:
    name: email
  kafka:
    topic: subscription-created-topic
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cloud:
    aws:
      region:
        static: eu-west-1
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      sqs:
        endpoint: https://sqs.eu-west-1.amazonaws.com
sqs:
  queue:
    url: https://sqs.eu-west-1.amazonaws.com/286646249098/subscription-events
    name: subscription-events


kafka:
  topic:
    name: subscription-created-topic
  group:
    id: email-service-group

server:
  port: 8082
